# Generated by Django 6.0.2 on 2026-02-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.ImageField(upload_to='menu_images/'),
        ),
    ]
