# Generated by Django 6.0.2 on 2026-02-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_menuitem_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='name',
        ),
    ]
